image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - apk add make

build:
  stage: build
  only:
    - master

  script:
    # Login to Docker Hub
    - echo "$DOCKER_HUB_TOKEN" | docker login --username "$DOCKER_HUB_USER" --password-stdin
    - export DOCKER_REGISTRY="$DOCKER_HUB_NAMESPACE"
    # Login to Gitlab registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_REGISTRY="$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
    # Build and push each flavour
    - (export FLAVOUR=sdk; make build && DOCKER_REGISTRY="$DOCKER_HUB_NAMESPACE" make push)
    - (export FLAVOUR=tools; make build && DOCKER_REGISTRY="$DOCKER_HUB_NAMESPACE" make push)
    - (export FLAVOUR=ndk; make build && DOCKER_REGISTRY="$DOCKER_HUB_NAMESPACE" make push)
    # android:latest = android:sdk
    - docker tag android:sdk "$DOCKER_HUB_NAMESPACE/android:latest"
    - docker push "$DOCKER_HUB_NAMESPACE/android:latest"